# this file will always be in the format:
# event:
#  - file.FunctionToCall
#  - file.FunctionToCall2
# 
- name: www-buildkite
  type: patchset-created
  filter:
    change.project: LineageOS/www
  callables:
    buildkite.StartPipeline:
      name: www-preview