# fly.toml file generated for lineageos-gerrit-stream-events on 2023-10-11T14:18:17-07:00

app = "lineageos-gerrit-stream-events"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
